---
apiVersion: v1
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: aW4tY2x1c3Rlcg==
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
kind: Secret
metadata:
  annotations:
    domain: {{ .Values.domain }}
    gitops-repo: {{ .Values.gitopsRepo }}
    kms-key-arn: {{ .Values.kmsKeyArn }}
    managed-by: argocd.argoproj.io
    node-security-group-id: {{ .Values.nodeSecurityGroupId }}
    oidc-provider: {{ .Values.oidcProvider }}
    vpc-cidr: {{ .Values.vpcCidr }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    aws-account-id: {{ .Values.awsAccountId | quote }}
    aws-region: {{ .Values.awsRegion }}
    cluster-name: {{ .Values.environmentName }}
    domain: {{ .Values.domain }}
    efs-file-system-id: {{ .Values.efsFileSystemId }}
    env-name: {{ .Values.environmentName }}
    vpc-id: {{ .Values.vpcId }}
  name: cluster-{{ .Values.environmentName }}
  namespace: argocd
type: Opaque
